name: Build and Push Docker Image

on:
  push:
    branches:
      - develop
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - develop
      - main
    types:
      - labeled

env:
  REGISTRY_IMAGE: ${{ secrets.DOCKER_USERNAME }}/status-frontend
  PR_ID: ${{ github.event.pull_request.number }}
  TAG: ${GITHUB_REF#refs/tags/}

jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.event.pull_request && github.event.label.name == 'dockerize')  || github.event_name == 'push'

    strategy:
      fail-fast: false
      matrix:
        platform: ["amd64", "arm64"]

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.7
        with:
          show-progress: false

      - name: Configure QEMU ⚙️
        uses: docker/setup-qemu-action@v3.2.0

      - name: Configure Docker Buildx ⚙️
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to DockerHub 🔑
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image (Develop)
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY_IMAGE }}:develop

      - name: Build and Push Docker Image (Version Tags)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY_IMAGE }}:${{ env.TAG }}

      - name: Build and Push Docker Image for Pull Request
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY_IMAGE }}:PR.${{ env.PR_ID }}

